### ISSUE TITLE
Error: code length overflow.

### ISSUE THREAD

**Issue by akicsike** [konstantin-nizhinskiy/qr-code-and-vcard#3]
Hello,

I got an error message on console.log when I use the photo object with base64 string.
Could you fix this error? or could you tell me how to use properly.

`QrCode2.js:494 Uncaught (in promise) Error: code length overflow. (26884>4184)
    at createData (QrCode2.js:494)
    at makeImpl (QrCode2.js:210)
    at getBestMaskPattern (QrCode2.js:244)
    at Object._this.make (QrCode2.js:569)
    at QrCode.createQr (QrCode2.js:2271)
    at QrCode.createVCardQrOwn (QrCode2.js:2652)
    at vcard (<anonymous>:339:60)
    at HTMLInputElement.<anonymous> (<anonymous>:83:5)`

`var  testCard = {
        version: '2.1',
        lastName: 'lastName',
        middleName: '',
        firstName: 'firstName',
        workPhone: '312-555-1212444',
        cellPhone: '312-555-1212444',
        workEmail: 'john.doe@workmail',
        title: 'title',
        photo: {
            url: base64_string,
            mediaType: 'JPEG',
            base64: true
        }
    };`

Thank you!

**Comment by konstantin-nizhinskiy** [comment]
Hi,

This message is not an error but a QR code size limit. You cannot create a QR code with Base64Url due to the fact that you get a lot of data and for this you need to create a huge QR code. In order to transfer an image in a contact, you must specify the URL where to store the picture and the base64 attribute (true / false) indicates that your URL will return
